spring.application.name=taskmanager

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.awevobsjxflctsnsuwdu
spring.datasource.password=postgresql@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logging
logging.level.root=info
logging.file.name=application.log
